name = "presoak"
main = "_worker.js"
compatibility_date = "2026-09-21"
no_bundle = true
workers_dev = false
preview_urls = true


[[kv_namespaces]]
binding = "kv"
#修改为自己创建的kv id
id = "cc298fdabafd46589c15fe3c145d32bd"

[vars]
# 修改为自己的
UUID = "3b94b54e-854f-48fd-a163-fd217e8b9cb9"
TR_PASS = "GnVG8kLFogMtthPe"
FALLBACK="zln.de5.net"


[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true
